-- Fluxx reference database schema (PostgreSQL).
--
-- Generated from the Fluxx Doctrine ORM mappings (vendor/sevj/fluxx/src/Entity).
-- This file is a reference schema for a fresh install. It targets PostgreSQL,
-- the primary platform validated for the bundle. For MySQL or SQLite, run
-- `bin/console doctrine:schema:create --dump-sql` in the host application; the
-- bundle mapping supports all three platforms through Doctrine DBAL.
--
-- Ordering: independent tables first, then relations and foreign keys.

-- ---------------------------------------------------------------------------
-- fluxx_user
-- ---------------------------------------------------------------------------
CREATE TABLE fluxx_user (
    id          INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email       VARCHAR(180) NOT NULL,
    roles       JSON NOT NULL,
    password    VARCHAR(255) NOT NULL,
    display_name VARCHAR(180) DEFAULT NULL,
    enabled     BOOLEAN DEFAULT TRUE NOT NULL,
    created_at  TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uniq_fluxx_user_email ON fluxx_user (email);

-- ---------------------------------------------------------------------------
-- fluxx_setting
-- ---------------------------------------------------------------------------
CREATE TABLE fluxx_setting (
    id          INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    setting_key VARCHAR(120) NOT NULL,
    value       JSON NOT NULL,
    updated_at  TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uniq_fluxx_setting_key ON fluxx_setting (setting_key);

-- ---------------------------------------------------------------------------
-- fluxx_workflow_run
-- ---------------------------------------------------------------------------
CREATE TABLE fluxx_workflow_run (
    id            INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    run_id        VARCHAR(64) NOT NULL,
    workflow_name VARCHAR(180) NOT NULL,
    source_system VARCHAR(180) NOT NULL,
    target_system VARCHAR(180) NOT NULL,
    trigger       VARCHAR(50) NOT NULL,
    status        VARCHAR(30) NOT NULL,
    batch_id       VARCHAR(180) DEFAULT NULL,
    metadata      JSON NOT NULL,
    created_at    TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    started_at    TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    finished_at   TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    lock_key      VARCHAR(190) DEFAULT NULL,
    lock_scope    VARCHAR(40) DEFAULT NULL,
    error_message TEXT DEFAULT NULL,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uniq_fluxx_workflow_run_run_id ON fluxx_workflow_run (run_id);
CREATE INDEX idx_fluxx_workflow_run_lock_key ON fluxx_workflow_run (lock_key);

-- ---------------------------------------------------------------------------
-- fluxx_workflow_execution_lock
-- ---------------------------------------------------------------------------
CREATE TABLE fluxx_workflow_execution_lock (
    id                   INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    workflow_name        VARCHAR(180) NOT NULL,
    owner_run_id         VARCHAR(64) NOT NULL,
    lock_key             VARCHAR(190) NOT NULL,
    scope                VARCHAR(40) NOT NULL,
    business_partition_key VARCHAR(180) DEFAULT NULL,
    acquired_at          TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    released_at         TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    release_reason       VARCHAR(50) DEFAULT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX idx_fluxx_workflow_execution_lock_key ON fluxx_workflow_execution_lock (lock_key);
CREATE INDEX idx_fluxx_workflow_execution_lock_owner_run_id ON fluxx_workflow_execution_lock (owner_run_id);

-- ---------------------------------------------------------------------------
-- fluxx_runtime_worker_state
-- ---------------------------------------------------------------------------
CREATE TABLE fluxx_runtime_worker_state (
    id                          INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    worker_name                 VARCHAR(190) NOT NULL,
    transport_name              VARCHAR(64) NOT NULL,
    receiver_name               VARCHAR(64) DEFAULT NULL,
    host                        VARCHAR(180) NOT NULL,
    pid                         INT NOT NULL,
    status                      VARCHAR(32) NOT NULL,
    current_message_class        VARCHAR(255) DEFAULT NULL,
    current_transport_message_id VARCHAR(190) DEFAULT NULL,
    workflow_code                VARCHAR(180) DEFAULT NULL,
    run_id                       VARCHAR(64) DEFAULT NULL,
    step_code                    VARCHAR(180) DEFAULT NULL,
    started_processing_at        TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    last_heartbeat_at           TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    memory_bytes                INT DEFAULT NULL,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uniq_fluxx_runtime_worker_state_worker_name ON fluxx_runtime_worker_state (worker_name);
CREATE INDEX idx_fluxx_runtime_worker_state_transport_name ON fluxx_runtime_worker_state (transport_name);
CREATE INDEX idx_fluxx_runtime_worker_state_last_heartbeat_at ON fluxx_runtime_worker_state (last_heartbeat_at);

-- ---------------------------------------------------------------------------
-- fluxx_workflow_step_run
-- ---------------------------------------------------------------------------
CREATE TABLE fluxx_workflow_step_run (
    id                          INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    step_type                   VARCHAR(50) NOT NULL,
    step_name                   VARCHAR(180) NOT NULL,
    position                    INT NOT NULL,
    status                      VARCHAR(30) NOT NULL,
    idempotence_key             VARCHAR(190) DEFAULT NULL,
    deduplication_status        VARCHAR(20) NOT NULL,
    processed_count             INT DEFAULT 0 NOT NULL,
    success_count               INT DEFAULT 0 NOT NULL,
    error_count                 INT DEFAULT 0 NOT NULL,
    duration_ms                 INT DEFAULT NULL,
    memory_peak_bytes           INT DEFAULT NULL,
    retry_count                 INT DEFAULT 0 NOT NULL,
    last_retry_at               TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    next_retry_at               TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    metadata                    JSON NOT NULL,
    created_at                  TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    started_at                  TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    finished_at                 TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    error_message               TEXT DEFAULT NULL,
    workflow_run_id             INT NOT NULL,
    deduplicated_from_step_run_id INT DEFAULT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IDX_1B5BACDEA5E64407 ON fluxx_workflow_step_run (workflow_run_id);
CREATE INDEX idx_fluxx_workflow_step_run_idempotence_key ON fluxx_workflow_step_run (step_name, idempotence_key);
CREATE INDEX idx_fluxx_workflow_step_run_dedup_from ON fluxx_workflow_step_run (deduplicated_from_step_run_id);

-- ---------------------------------------------------------------------------
-- fluxx_workflow_payload
-- ---------------------------------------------------------------------------
CREATE TABLE fluxx_workflow_payload (
    id                  INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    target_step_type    VARCHAR(50) NOT NULL,
    target_step_name    VARCHAR(180) NOT NULL,
    sequence            INT NOT NULL,
    format              VARCHAR(20) NOT NULL,
    compression         VARCHAR(20) NOT NULL,
    storage_mode        VARCHAR(20) NOT NULL,
    content             TEXT NOT NULL,
    content_hash        VARCHAR(64) NOT NULL,
    record_count        INT DEFAULT 0 NOT NULL,
    raw_size            INT NOT NULL,
    stored_size         INT NOT NULL,
    metadata            JSON NOT NULL,
    created_at          TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    workflow_run_id     INT NOT NULL,
    source_step_run_id  INT NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IDX_A77B4AFCA5E64407 ON fluxx_workflow_payload (workflow_run_id);
CREATE INDEX IDX_A77B4AFC9582631E ON fluxx_workflow_payload (source_step_run_id);

-- ---------------------------------------------------------------------------
-- Foreign keys
-- ---------------------------------------------------------------------------
ALTER TABLE fluxx_workflow_step_run
    ADD CONSTRAINT FK_1B5BACDEA5E64407
    FOREIGN KEY (workflow_run_id) REFERENCES fluxx_workflow_run (id) ON DELETE CASCADE NOT DEFERRABLE;
ALTER TABLE fluxx_workflow_step_run
    ADD CONSTRAINT FK_1B5BACDEB76A6314
    FOREIGN KEY (deduplicated_from_step_run_id) REFERENCES fluxx_workflow_step_run (id) ON DELETE SET NULL NOT DEFERRABLE;
ALTER TABLE fluxx_workflow_payload
    ADD CONSTRAINT FK_A77B4AFCA5E64407
    FOREIGN KEY (workflow_run_id) REFERENCES fluxx_workflow_run (id) ON DELETE CASCADE NOT DEFERRABLE;
ALTER TABLE fluxx_workflow_payload
    ADD CONSTRAINT FK_A77B4AFC9582631E
    FOREIGN KEY (source_step_run_id) REFERENCES fluxx_workflow_step_run (id) ON DELETE CASCADE NOT DEFERRABLE;
